{% set name = "easygems" %}
{% set version = "0.0.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/easygems-{{ version }}.tar.gz
  sha256: f06a449f0d4ab123925086d2fc6c1a7085a790301f0e9cdc1ed15803426beb03

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - poetry-core >=1.0.0
    - poetry-dynamic-versioning >=1.0.0,<2.0.0
    - pip
  run:
    - python >=3.10
    - numpy
    - scipy
    - xarray
    - cf_xarray
    - healpy >=1.16.3
    - matplotlib-base
    - cartopy

test:
  imports:
    - easygems
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mpimet/easygems
  summary: Processing tools around km-scale earth system modeling
  license: 'MIT'
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mahf708
