{% set python_min = "3.10" %}
{% set name = "easygems" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/easygems-{{ version }}.tar.gz
  sha256: 048e5f92b229d9b3de40b3f656cbed69eac8ef7bf3b432d552d4bcda35498352

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - poetry-dynamic-versioning >=1.0.0,<2.0.0
    - pip
  run:
    - healpix
    - python >={{ python_min }}
    - numpy
    - scipy
    - xarray
    - cf_xarray
    - matplotlib-base
    - cartopy

test:
  imports:
    - easygems
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/mpimet/easygems
  summary: Processing tools around km-scale earth system modeling
  license: 'MIT'
  license_file: LICENSE

extra:
  recipe-maintainers:
    - lkluft
    - mahf708
